version: "3"
services:

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=stationSki

    volumes:
      - db:/var/lib/mysqldb

  spring_app:
    image: youssefalmia/5twin5-g7-skistation:latest
    container_name: SkiStation
    restart: on-failure
    networks:
      - mynetwork
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

networks:
  mynetwork:
    driver: bridge
