version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  spring_app:
    image: youssefalmia/5twin5-g7-skistation:latest
    container_name: SkiStation
    restart: on-failure
    networks:
      - mynetwork
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

networks:
  mynetwork:
    driver: bridge
