version: "1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - /home/vagrant/mysql/data:/var/lib/mysql
  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - 8081:8081
  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9092:9092
