version: '3.3'

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    image: rayenbourguiba/skistationdevopsimage
    container_name: spring-app
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true

volumes:
  db:
