version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=stationSki

    volumes:
      - db:/var/lib/mysqldb

  spring_app:
    image: tahersn/skistation:latest
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    volumes:
     - .m2:/root/.m2

volumes:
  db:
