version: "1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - /home/vagrant/mysql/data:/var/lib/mysql

  spring_app:
    image: fouratbendhafer11/5twin5-onezero-skistation:latest
    container_name: skistation
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
